#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)
        if ! omv_config_exists "/config/services/virtualhosts"; then
            omv_config_add_element "/config/services" "virtualhosts"
            omv_config_add_element "/config/services/virtualhosts" "enable" "0"
            omv_config_add_element "/config/services/virtualhosts" "server_name_default_port" "8000"
            omv_config_add_element "/config/services/virtualhosts" "virtual_hosts"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
